# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
env:
  global:
    - SECRET_KEY=dumb_secret_key_for_travis
    - STRIPE_PUBLISHABLE_KEY=dumb_stripe_publishable_key_for_travis
    - STRIPE_SECRET_KEY=dumb_stripe_secret_key_for_travis
before_install: npm install
install:
  - pip install -r requirements/dev.txt
  - node node_modules/webpack/bin/webpack.js
before_script: cd src
script:
  - python manage.py lint
  - coverage run --source=. manage.py test
after_script:
  - coveralls
