# pylint: disable=C0103
# Generated by Django 2.0.2 on 2018-02-24 09:42

import django.db.models.deletion
from django.db import migrations, models

import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField(db_index=True, default=True, verbose_name='In stock')),
                ('price', models.FloatField()),
                ('slug', models.SlugField(unique=True)),
                ('category',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='goods',
                     to='categories.Category')),
                ('tags',
                 taggit_selectize.managers.TaggableManager(
                     blank=True,
                     help_text='A comma-separated list of tags.',
                     through='taggit.TaggedItem',
                     to='taggit.Tag',
                     verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'goods',
                'ordering': ('-price', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='good',
            unique_together={('category', 'name', 'price')},
        ),
    ]
