# pylint: disable=C0103
# Generated by Django 2.0.2 on 2018-02-24 11:31

from django.db import migrations

import autoslug.fields

import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=goods.models.get_slug, unique=True),
        ),
    ]
