# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 18:12
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    good_class = apps.get_model('goods', 'Good')
    for good in good_class.objects.all():
        good.slug = '-'.join((slugify(good.category.name, allow_unicode=True), slugify(good.name, allow_unicode=True)))
        good.save()


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_good_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug),
    ]
