# pylint: disable=C0103
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_good_slug_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(max_length=50, default=None, unique=True),
            preserve_default=False,
        ),
    ]
